// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoba2QYzOYA5vQa9_lwLJPd8viSAoLP8k',
    appId: '1:146393585239:web:41b848e1fc94f08024b512',
    messagingSenderId: '146393585239',
    projectId: 'push-notification-d782a',
    authDomain: 'push-notification-d782a.firebaseapp.com',
    storageBucket: 'push-notification-d782a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn404D2CYI3torrZlVsKf8XxvVVRDph18',
    appId: '1:146393585239:android:b16bf16df0ba19a324b512',
    messagingSenderId: '146393585239',
    projectId: 'push-notification-d782a',
    storageBucket: 'push-notification-d782a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL6RiIA-54aPqZFX8zI9l8jkYC7XcdoDg',
    appId: '1:146393585239:ios:d30c1183ec703e5a24b512',
    messagingSenderId: '146393585239',
    projectId: 'push-notification-d782a',
    storageBucket: 'push-notification-d782a.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL6RiIA-54aPqZFX8zI9l8jkYC7XcdoDg',
    appId: '1:146393585239:ios:a0ad3c89bec9dfc724b512',
    messagingSenderId: '146393585239',
    projectId: 'push-notification-d782a',
    storageBucket: 'push-notification-d782a.appspot.com',
    iosBundleId: 'com.example.notification.RunnerTests',
  );
}
